# Controls the current font / size.
font:
  normal:
    family: IBM Plex Mono
    style: Regular

  bold:
    family: IBM Plex Mono
    style: Bold

  italic:
    family: IBM Plex Mono
    style: Italic

  bold_italic:
    family: IBM Plex Mono
    style: Bold Italic

  size: 14.0
