# Load font settings separately. This lets us change
# the font settings on different operating systems.
import:
 - ~/.alacritty-font.yml

# Set environment variables.
env:
  TERM: xterm-256color

# Set scrolling variables.
scrolling:
  history: 10000

# Draw bold text using bright color variants.
draw_bold_text_with_bright_colors: true

# One Dark Vivid
colors:
  # Default colors
  primary:
    background: "#282c34"
    foreground: "#abb2bf"

  # Normal colors
  normal:
    black:   "#282c34"
    red:     "#ef596f"
    green:   "#89ca78"
    yellow:  "#e5c07b"
    blue:    "#61afef"
    magenta: "#d55fde"
    cyan:    "#2bbac5"
    white:   "#abb2bf"
  bright:
    black:   "#282c34"
    red:     "#ef596f"
    green:   "#89ca78"
    yellow:  "#e5c07b"
    blue:    "#61afef"
    magenta: "#d55fde"
    cyan:    "#2bbac5"
    white:   "#abb2bf"

# Doom One
# colors:
#   primary:
#     background: '#282c34'
#     foreground: '#bbc2cf'
#   cursor:
#     text: CellBackground
#     cursor: '#528bff'
#   selection:
#     text: CellForeground
#     background: '#3e4451'
#   normal:
#     black:   '#282c34'
#     red:     '#ff6c6b'
#     green:   '#98be65'
#     yellow:  '#da8548'
#     blue:    '#51afef'
#     magenta: '#c678dd'
#     cyan:    '#5699af'
#     white:   '#bbc2cf'
#   bright:
#     black:   '#5b6268'
#     red:     '#da8548'
#     green:   '#4db5bd'
#     yellow:  '#ecbe7b'
#     blue:    '#3071db'
#     magenta: '#a9a1e1'
#     cyan:    '#46d9ff'
#     white:   '#dfdfdf'

# Setup various keybindings. You can look here for other keybinding examples:
# https://github.com/alacritty/alacritty/issues/62#issuecomment-347552058
key_bindings:
  # Move forward by word.
  - { key: F, mods: Super, chars: "\x1bf" }

  # Move backward by word.
  - { key: B, mods: Super, chars: "\x1bb" }

  # Delete forward by word.
  - { key: D, mods: Super, chars: "\x1bd" }

# Use option as alt on both sides.
window:
  option_as_alt: Both
