[font]
size = 15.0

[font.bold]
family = "BlexMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "BlexMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "BlexMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "BlexMono Nerd Font Mono"
style = "Regular"
