[font]
size = 20.0

[font.bold]
family = "IBM Plex Mono"
style = "Bold"

[font.bold_italic]
family = "IBM Plex Mono"
style = "Bold Italic"

[font.italic]
family = "IBM Plex Mono"
style = "Italic"

[font.normal]
family = "IBM Plex Mono"
style = "Regular"
