;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-brace
        c-electric-colon
        c-electric-delete-forward
        c-electric-paren
        c-end-of-statement
        c-indent-line-or-region
        end-of-visual-line
        hydra-marking/body
        hydra-marking/er/expand-region
        hydra-marking/er/mark-symbol
        kill-region
        org-beginning-of-line
        org-kill-line
        org-self-insert-command
        paredit-backward-kill-word
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-kill
        paredit-semicolon
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-lt-gt
        hydra-multiple-cursors/mc/edit-lines-and-exit
        hydra-multiple-cursors/mc/mark-all-like-this-and-exit
        hydra-multiple-cursors/mc/mark-next-like-this
        hydra-multiple-cursors/mc/mark-previous-like-this
        hydra-multiple-cursors/mc/skip-to-next-like-this
        hydra-multiple-cursors/mc/skip-to-previous-like-this
        hydra-multiple-cursors/mc/unmark-next-like-this
        hydra-multiple-cursors/mc/unmark-previous-like-this
        suspend-frame
        ))
